#%RAML 1.0 NamedExample
value:
  -
    id: "AVGPVR"
    name: "Avengers"
    language: "English"
    theatre: "PVR"
    city: "Pune"
    show: "Morning"
    price: 120
    available_seats: 180
  -
    id: "IRMIMX"
    name: "Iron Man"
    language: "English"
    theatre: "IMAX"
    city: "Hyderabad"
    show: "Morning"
    price: 100
    available_seats: 180